language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
  slack:
    secure: bqCoqqMkv5Tl7ygyDLCy0HoPr0ga1FIq+rX2a2FEQ5xySuUesne2dJNbXFg/nf7XWl4zYtk7SeNIqbxdDIY388ev86jgylEmLjxYoABTw1WnSn6OJwqz+rKZJNkZ089KZLqen8m8opLLUgaSFIC6Ps1K2bTNftqC0Vxk6L8MfBmL/FatDtbN5KYeaiemwpjnYtHJdjxcN9vrRSKZe2qbus9yzP34U7adXECD4QGsSPlYQUDrRkxHTkboBzz/N3nIXsRG07KM8EU6RocxBgDxJNd8faIG2oeJNXXFhOpB5ZpMwBu5dJMelpxqtUinr4GPhwpIbmOeqkPwzzw+KINqvWydbHFafdMoE63PpOKshWc5mq6gv1iU5q6LeuH62a0eBqjaPlJ7k1qHJSoc4L+70eOQgGYW/y/T1cjVBRNcbQCTCFnijq8asklXW0J7DmvyzahnoBq3MbCBSVi14Oj5Oy8lx918kcdJ5waPNN2rvY7BGlx+kmpmdy0CksiGH7+/XNPaOlrv+ocAYIrmCJZAJPMXoijarkrPYYDH7fwYTg4rfXYUztn8S4gha9tYoyFEiDDgqRPLuN+8+yhne7Ij94Ek12IdroSTWfPrNDfndnJdb1f8n4JDmLUU0CcRboUQmKZPMVo0LCrLXawp52RZ00aJNaJRGwNRvD6jtAq8Ox0=
env:
  global:
  - secure: KYYWVJcqvgqaBIF94cNcD2/sHwJJ8EGPLdmUs+B+QMLA2j5JiNMMb3zYuBDkwpG8W+KTVpwwmAD5bkA6IfsHrKBVo11imSPN3Q9l2BIA+qmgl5OHbJqOuKx3SB/A8pN9/SZ73ZloFScmfTpLxF6p57rC+iELHYX8sg8Gf6XKaGUVjgg9gZvTKfRZdvNNl1FpoNsItUagqWSzOMdGaEQawRtpM5pMAa++bAqbzHjPLP8Je4+5HUiw8jNyekP5OeDpx8Vhf/wbwsgYh4EmMnT02UkQgWfSDQO6i73a2ojIhuRvOpY0Tus118dMqkJuDfdFaeM9X4JbUSp4ta9Wi6232Kfn9IEpn6yCrvTIT7n76ylf6QEIWaudcGZg2pwOWWzTmpdBEfH2Gu03CCNYVdT9iMAITz7G9mmxup6o9rT4WJKDZc4TGUyK+qQ+hIjUXN9VVzuR+cOPRdWZmys/zP9W//i3BZle5DH3ifdGFuE6t7Xc5v640kbKAN/Z1Pv29INq9XQHbm4Xgj3jtN7j4F5l2zhIKp42EvZFHmMvYTKt3WkbUgU0vsXveMNRmC8dgJMdWuynjTufU6Zv/WTARe1GnPWWc7b7A+tcfpi9NEsLMgurlpavDFCTeloz7Wa9WPgGoQXv2Pbkl5ZdHNvpELBga9icNh7OVLhmj5NdwUP7Oe4=
  - secure: UpB+LtBegRC5/OcYmNyVVjOVdnJj5JCh9FjCqxPOch5CXuCEAz9B79adg07R0MDOh8b7y0wYbBdK4dxuHBXOfc/n9GWkcPzNFKLoYMTlFlbVCcAz3vEyUL3lRNowZ4+VhMONj18HgMpDFhPwtoT2wvBGAonnKV44CT5itO8xXUaoapQG4EwwN2GUTMeS6+ubkYinCbcAj6HutCKAPvcqLuJehqk1Wbw/fwxnDE8/mEO6VhwAFEQGY1eo61PFqi+m5GPQpFdSHLWI3EIG8jgPNlqH4VsujwdttinCgk1RM6T9lTSa06hi/LTK2zyoFMLaNUafKAkZGKWX4Hx3Vp4L8+Kq1rjwRBfdA3fadC38wObxYK5gXPkfkmapFQRvni0JryyhnI4o47JHQXaWPZCPZXhRnvAsbSDHYD7NchC//iEtWnG9XYf5N3CmsYkRZMVmlWbu/vwZHdd5dVof4vnEb/biV1YjB38cANdl1k8HPsinXM1Cqz399jSLcvWrBwxHlJt7KhWL5rYljUsnmFWS5PEfnSz7KPW4YAmu8EmqgmVAJB/TpQk9hmajpYO6sIx9GjR0ZlIlR0OJ/mT+eWFkRQZqDQoOXjSGrJ15OtEShWFxTAGd3faXOvhNf9NP5CUnzd7uUYqHbVoi/Jk9q3TFg+AKBSmrdPuM+EGrn1dv28s=
  - secure: gaoRBKWGpn8C3u2y4X7mCUsnXf96Kn3AbfLXSRMVS6gHa1IooElLXhLu4HGPgI8lXEJPEEBRwg9vHOCup/YjzEAhKuhWPpTbz2t9T4Wvb6jXsRMuNAUji4OAKiz0Loa00lcm4Brms9gxss9NyZpmBwecmZMHjTQ9cXBSqCtbiF3gIZDQPTP2wx2wLGP13K7OjQRm+z8R8IL7gT0GX7A2gH3a1473YyRpKark1EfmdxqaX19B4SKCg9FjxEK9r0GxWdzaLeaRlGESPg4l5O5qIlUzJiW3cULCkr8//2UTaAULGHcyVYlwYPHGhMC4drLex5cFjzvy4XVHYdsKe6tXAJdxpCASZ2+CJKWqRmPmV53p/m+bRugZfCeB4reoTAjDVc7Qcgp3sX2Go+X7Xi4P1nSJfJhqqLf1NuwhvmJoYSZ6NPUTrE9XiP4hlEW8MvPW9o3iiF9+wIyAvnbAXPDOHmygiT+JwFS/DZiZ6jOnuMgUJI+VVuGX2ij5N05XdV9yFcPcd6mIT73zdRqX2Tv5iLebnpC/GjeYlJh5cy3oIBad0NuRDXGmlFYMkQHl/2i2/5wwC4j0WI69gXy7ej0mfw2uByXjPBCRbyHzIByXlidhkMFLdj7V0bPuEcW2jYcNWfcmWn4nXKv/HEMTd98lnW2wRhXwsd8oseXeSW17lqc=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-licence-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and deploy
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and deploy
  if: branch = master
